### ISSUE TITLE
s6-overlay v3 is coming

### ISSUE THREAD

**Issue by shinsenter** [serversideup/s6-overlay#1]
I think it would be nice if this image has the latest version of s6-overlay installed.
https://github.com/just-containers/s6-overlay/releases/tag/v3.0.0.0

**Comment by jaydrogers** [comment]
Thanks for letting me know about this release! It's exciting to see they released 3.0 a few days ago.

I will set up a beta channel to start testing this new release. Thanks!

**Comment by jaydrogers** [comment]
# Update:
I have a PR open for this, which I will track updates there: https://github.com/serversideup/docker-baseimage-s6-overlay-ubuntu/pull/3

**Comment by shinsenter** [comment]
Is there update on this ticket?

**Comment by jaydrogers** [comment]
Sorry, my schedule got busy over the last few days. Hoping to get to this soon!
